title: DissecTLS

author: Markus Sosnowski

description: >-
  Additional Material
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dissectls.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:  syncall

theme: minima
